#ifndef TARGET_CONFIG_H
#define TARGET_CONFIG_H target.h
#endif

#define GL_STRINGIFY_INCLUDE_(x) #x
#define GL_STRINGIFY_INCLUDE(x) GL_STRINGIFY_INCLUDE_(x)
#include GL_STRINGIFY_INCLUDE(TARGET_CONFIG_H)
#undef GL_STRINGIFY_INCLUDE
#undef GL_STRINGIFY_INCLUDE_
